# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fsp-rule.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import fsp_common_pb2 as fsp__common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='fsp-rule.proto',
  package='com.fsmeeting.fsp.proto.rule',
  syntax='proto3',
  serialized_pb=_b('\n\x0e\x66sp-rule.proto\x12\x1c\x63om.fsmeeting.fsp.proto.rule\x1a\x10\x66sp-common.proto\"\xa4\x01\n\x0eGetMediaServer\x12\x11\n\tclient_ip\x18\x01 \x01(\t\x12\x13\n\x0bserver_type\x18\x02 \x01(\t\x12\x10\n\x08group_id\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\t\x12\x0e\n\x06\x61pp_id\x18\x05 \x01(\t\x12\x12\n\ncompany_id\x18\x06 \x01(\t\x12\x0f\n\x07room_id\x18\x07 \x01(\t\x12\x12\n\nmedia_type\x18\x08 \x01(\x05\"\x85\x01\n\x11GetMediaServerRsp\x12@\n\x08response\x18\x01 \x01(\x0b\x32..com.fsmeeting.fsp.proto.common.CommonResponse\x12\x14\n\x0cmediaServers\x18\x02 \x03(\t\x12\x18\n\x10mediaServerAddrs\x18\x03 \x03(\t\"\xa0\x01\n\nRuleSelect\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x16\n\x0esourceInstance\x18\x02 \x01(\t\x12\x10\n\x08instance\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x0f\n\x07room_id\x18\x05 \x01(\t\x12\x12\n\ncompany_id\x18\x06 \x01(\t\x12\x0e\n\x06\x61pp_id\x18\x07 \x01(\t\x12\x12\n\nmedia_type\x18\x08 \x01(\x05\"w\n\rRuleSelectRsp\x12@\n\x08response\x18\x01 \x01(\x0b\x32..com.fsmeeting.fsp.proto.common.CommonResponse\x12\x10\n\x08instance\x18\x02 \x01(\t\x12\x12\n\nconnectStr\x18\x03 \x01(\t*\xcb\x01\n\x0fProtoDictionary\x12\x19\n\x15\x45num2UnknownInterface\x10\x00\x12\x18\n\x13\x45num2GetMediaServer\x10\xa8\x46\x12\x1b\n\x16\x45num2GetMediaServerRsp\x10\xa9\x46\x12\x17\n\x12\x45num2RuleSelection\x10\xaa\x46\x12\x1a\n\x15\x45num2RuleSelectionRsp\x10\xab\x46\x12\x16\n\x11\x45num2GetVNCServer\x10\xac\x46\x12\x19\n\x14\x45num2GetVNCServerRsp\x10\xad\x46\x42)\n\x1c\x63om.fsmeeting.fsp.proto.ruleP\x01\xf8\x01\x01\xa2\x02\x03GPBb\x06proto3')
  ,
  dependencies=[fsp__common__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_PROTODICTIONARY = _descriptor.EnumDescriptor(
  name='ProtoDictionary',
  full_name='com.fsmeeting.fsp.proto.rule.ProtoDictionary',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Enum2UnknownInterface', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Enum2GetMediaServer', index=1, number=9000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Enum2GetMediaServerRsp', index=2, number=9001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Enum2RuleSelection', index=3, number=9002,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Enum2RuleSelectionRsp', index=4, number=9003,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Enum2GetVNCServer', index=5, number=9004,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Enum2GetVNCServerRsp', index=6, number=9005,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=654,
  serialized_end=857,
)
_sym_db.RegisterEnumDescriptor(_PROTODICTIONARY)

ProtoDictionary = enum_type_wrapper.EnumTypeWrapper(_PROTODICTIONARY)
Enum2UnknownInterface = 0
Enum2GetMediaServer = 9000
Enum2GetMediaServerRsp = 9001
Enum2RuleSelection = 9002
Enum2RuleSelectionRsp = 9003
Enum2GetVNCServer = 9004
Enum2GetVNCServerRsp = 9005



_GETMEDIASERVER = _descriptor.Descriptor(
  name='GetMediaServer',
  full_name='com.fsmeeting.fsp.proto.rule.GetMediaServer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_ip', full_name='com.fsmeeting.fsp.proto.rule.GetMediaServer.client_ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_type', full_name='com.fsmeeting.fsp.proto.rule.GetMediaServer.server_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='group_id', full_name='com.fsmeeting.fsp.proto.rule.GetMediaServer.group_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='com.fsmeeting.fsp.proto.rule.GetMediaServer.user_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='app_id', full_name='com.fsmeeting.fsp.proto.rule.GetMediaServer.app_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='company_id', full_name='com.fsmeeting.fsp.proto.rule.GetMediaServer.company_id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='room_id', full_name='com.fsmeeting.fsp.proto.rule.GetMediaServer.room_id', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='media_type', full_name='com.fsmeeting.fsp.proto.rule.GetMediaServer.media_type', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=231,
)


_GETMEDIASERVERRSP = _descriptor.Descriptor(
  name='GetMediaServerRsp',
  full_name='com.fsmeeting.fsp.proto.rule.GetMediaServerRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='com.fsmeeting.fsp.proto.rule.GetMediaServerRsp.response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mediaServers', full_name='com.fsmeeting.fsp.proto.rule.GetMediaServerRsp.mediaServers', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mediaServerAddrs', full_name='com.fsmeeting.fsp.proto.rule.GetMediaServerRsp.mediaServerAddrs', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=367,
)


_RULESELECT = _descriptor.Descriptor(
  name='RuleSelect',
  full_name='com.fsmeeting.fsp.proto.rule.RuleSelect',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_id', full_name='com.fsmeeting.fsp.proto.rule.RuleSelect.stream_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sourceInstance', full_name='com.fsmeeting.fsp.proto.rule.RuleSelect.sourceInstance', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='instance', full_name='com.fsmeeting.fsp.proto.rule.RuleSelect.instance', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='com.fsmeeting.fsp.proto.rule.RuleSelect.type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='room_id', full_name='com.fsmeeting.fsp.proto.rule.RuleSelect.room_id', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='company_id', full_name='com.fsmeeting.fsp.proto.rule.RuleSelect.company_id', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='app_id', full_name='com.fsmeeting.fsp.proto.rule.RuleSelect.app_id', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='media_type', full_name='com.fsmeeting.fsp.proto.rule.RuleSelect.media_type', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=370,
  serialized_end=530,
)


_RULESELECTRSP = _descriptor.Descriptor(
  name='RuleSelectRsp',
  full_name='com.fsmeeting.fsp.proto.rule.RuleSelectRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='com.fsmeeting.fsp.proto.rule.RuleSelectRsp.response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='instance', full_name='com.fsmeeting.fsp.proto.rule.RuleSelectRsp.instance', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='connectStr', full_name='com.fsmeeting.fsp.proto.rule.RuleSelectRsp.connectStr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=532,
  serialized_end=651,
)

_GETMEDIASERVERRSP.fields_by_name['response'].message_type = fsp__common__pb2._COMMONRESPONSE
_RULESELECTRSP.fields_by_name['response'].message_type = fsp__common__pb2._COMMONRESPONSE
DESCRIPTOR.message_types_by_name['GetMediaServer'] = _GETMEDIASERVER
DESCRIPTOR.message_types_by_name['GetMediaServerRsp'] = _GETMEDIASERVERRSP
DESCRIPTOR.message_types_by_name['RuleSelect'] = _RULESELECT
DESCRIPTOR.message_types_by_name['RuleSelectRsp'] = _RULESELECTRSP
DESCRIPTOR.enum_types_by_name['ProtoDictionary'] = _PROTODICTIONARY

GetMediaServer = _reflection.GeneratedProtocolMessageType('GetMediaServer', (_message.Message,), dict(
  DESCRIPTOR = _GETMEDIASERVER,
  __module__ = 'fsp_rule_pb2'
  # @@protoc_insertion_point(class_scope:com.fsmeeting.fsp.proto.rule.GetMediaServer)
  ))
_sym_db.RegisterMessage(GetMediaServer)

GetMediaServerRsp = _reflection.GeneratedProtocolMessageType('GetMediaServerRsp', (_message.Message,), dict(
  DESCRIPTOR = _GETMEDIASERVERRSP,
  __module__ = 'fsp_rule_pb2'
  # @@protoc_insertion_point(class_scope:com.fsmeeting.fsp.proto.rule.GetMediaServerRsp)
  ))
_sym_db.RegisterMessage(GetMediaServerRsp)

RuleSelect = _reflection.GeneratedProtocolMessageType('RuleSelect', (_message.Message,), dict(
  DESCRIPTOR = _RULESELECT,
  __module__ = 'fsp_rule_pb2'
  # @@protoc_insertion_point(class_scope:com.fsmeeting.fsp.proto.rule.RuleSelect)
  ))
_sym_db.RegisterMessage(RuleSelect)

RuleSelectRsp = _reflection.GeneratedProtocolMessageType('RuleSelectRsp', (_message.Message,), dict(
  DESCRIPTOR = _RULESELECTRSP,
  __module__ = 'fsp_rule_pb2'
  # @@protoc_insertion_point(class_scope:com.fsmeeting.fsp.proto.rule.RuleSelectRsp)
  ))
_sym_db.RegisterMessage(RuleSelectRsp)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\034com.fsmeeting.fsp.proto.ruleP\001\370\001\001\242\002\003GPB'))
# @@protoc_insertion_point(module_scope)
